version: "3.9"

services:
  api:
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A tasks.celery_app worker --loglevel=info
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
